# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ShopiTrello"
client_id = "cdbe8c337ddeddaa887cffff22dca575"
application_url = "https://trello-engine.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = ""

[access_scopes]
scopes = "read_products,read_orders,read_customers,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://trello-engine.dev/api/shopify/auth/callback",
  "https://trello-engine.dev/auth/callback",
  "https://trello-engine.dev/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/api/shopify/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/api/shopify/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/api/shopify/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/api/shopify/webhooks/shop/redact"

[pos]
embedded = false

